# Generated by Django 3.2.19 on 2024-04-23 03:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alter',
            fields=[
                ('id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('layer_no', models.CharField(max_length=45)),
                ('kernel_no', models.CharField(max_length=45)),
                ('channel_no', models.CharField(max_length=45)),
                ('num1', models.CharField(max_length=45)),
                ('num2', models.CharField(max_length=45)),
                ('input_no', models.CharField(max_length=45)),
                ('output_no', models.CharField(max_length=45)),
                ('weight', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'alter',
            },
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateField()),
                ('record_id', models.IntegerField()),
                ('error_num', models.IntegerField()),
                ('error_node', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='medical_record',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('gender', models.CharField(choices=[('1', '男'), ('2', '女')], max_length=2)),
                ('age', models.IntegerField()),
                ('desc', models.CharField(max_length=45)),
                ('otherdata', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'medical_record',
            },
        ),
        migrations.CreateModel(
            name='medicalrecord',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('gender', models.CharField(choices=[('1', '男'), ('2', '女')], max_length=2)),
                ('age', models.IntegerField()),
                ('result', models.CharField(max_length=45)),
                ('remark', models.CharField(max_length=45)),
                ('time', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=45)),
                ('feature1', models.CharField(max_length=45)),
                ('feature2', models.CharField(max_length=45)),
                ('verify_res', models.CharField(max_length=45)),
                ('verify_error_layer', models.CharField(max_length=200)),
                ('verify_error_kernel', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'medicalrecord',
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('identity', models.CharField(choices=[('1', '患者'), ('2', '医生'), ('3', '医院')], max_length=2)),
                ('email', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Userinfo',
            },
        ),
    ]
